### ISSUE TITLE
Use modified graphite-api package

### ISSUE THREAD

**Issue by pkittenis** [InfluxGraph/influxgraph#43]
## Feature Request

Graphite-API seems to be getting less maintenance these days and there are finished bug fixes and feature PRs that would benefit this project that have not been reviewed nor merged.

### Proposed changes

* Fork and embed graphite-api as a submodule to this project, remove from requirements
* Add following changes to forked graphite-api
  - Remove consolidation of data points by hard coded `consolidateBy` graphite function used by default in graphite-api before data is returned  (  #42  )
  - Make [cairo optional](https://github.com/brutasse/graphite-api/pull/198)
  - Remove index file must exist requirement as it's not used by either graphite-api or influxgraph
  - asPercent not accepting multiple series - [graphite-api/#150](https://github.com/brutasse/graphite-api/pull/150)

**Comment by tux1337** [comment]
Did you talked to @brutasse about the state of the graphite-api project? 
I would prefer to find another maintainer for the graphite-api repo instead of forking it. This would prevent incompatibilities between the fork and graphite-api. 
More users would benefit if graphite-api would be maintained well instead of forking it as subproject of influxgraph.

just my two cents...

**Comment by pkittenis** [comment]
That's a question for @brutasse . I do not like it either, and have no intention of maintaining or offering support for graphite-api-fork for anything other than its interaction with influxgraph.

The fork and new package is simply so it and InfluxGraph can be used as a one-stop application. Fact is graphite-api seems to be unmaintained, leaving forking as the only option.
