### ISSUE TITLE
Building and refreshing of index happens in every worker process putting high load on Influx

### ISSUE THREAD

**Issue by mateuszzawisza** [InfluxGraph/influxgraph#49]
Hello,

We're implementing influxgraph in our stack. We've found that building and refreshing index in InfluxDBFinder class happens in every worker that is spawned. For e.g if I run gunicorn with 10 processes like `bin/gunicorn -w 10` I get 10 workers all of them which will query influx and build index concurrently. This puts a lot of unneeded pressure on InfluxDB. On a single server, we could build it once and make workers load/refresh it from the file.

I'd like to contribute a solution to this but don't want to do anything that is not aligned with the vision of the authors. 

How about we make a configurable option to run a worker in a mode which only loads an index from disk and then we could create a separate worker that creates and refreshes the index.

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest and report.

Each process needs to load/build an index as memory is not shared between processes.

Note that there is already an exclusive lock held by each process so that they do not all build an index at same time. In other words, the load on influxdb is the same regardless of number of processes, though 10 processes means 10 consecutive index builds and 10 times *longer* load on the DB, not 10x the load.

However, there is no need to run so many gunicorn worker processes. Remember, gunicorn is an application server, not a web server. So it should be fronted by an actual web server like nginx/apache/uwsgi that handles connections and passes through to a limited number of gunicorn worker processes. 

This not only reduces load on influxdb, it also reduces memory and CPU requirements for influxgraph and gives better performance as the web servers are better able to handle multiple connections than gunicorn.

Loading from disk is not a viable solution - it is no faster than building index from scratch and still requires that index is duplicated between processes. Some older versions did do just that but was removed as it was slower.

So a better approach is to limit gunicorn to only a couple processes and handle multiple connections with a web server.

A better solution would be to re-design the index as an on-disk directory structure on a temporary file system so it not need be held in memory, can be written by one process and queried via the FS without loading by any other process. This will come at a cost of lookup performance for large trees however.

That is a significant amount of work but can probably reuse a lot of the parsing code - see whisper's directory structure implementation for what this looks like. If that is something you are able to get involved with I'd be happy to review and assist with a PR.

If you are up for it can also add you as contributor to the project and work together on a shared feature branch - it's been on my mind for a while but not much time to spend on influxgraph these days.
